# This workflow builds a Minecraft Forge mod project

name: "Build"

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version that should be used to compile the code [8, 16, 17]'
        required: true
        type: number

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set branch values
        id: branch_values
        run: |
          if [ ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }} ]; then
            echo "DEPENDENCY_GRAPH=generate-and-submit" >> $GITHUB_OUTPUT
          else
            echo "DEPENDENCY_GRAPH=disabled" >> $GITHUB_OUTPUT
          fi

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          dependency-graph: ${{ steps.branch_values.outputs.DEPENDENCY_GRAPH }}
