# This workflow builds a Minecraft Forge mod project

name: "Build"

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version that should be used to compile the code [8, 16, 17]'
        required: true
        type: number
    outputs:
      artifact-name:
        description: 'Name of uploaded artifact'
        value: gradle-build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Set branch values
        id: branch_values
        run: |
          if [ ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }} ]; then
            echo "DEPENDENCY_GRAPH=generate-and-submit" >> $GITHUB_OUTPUT
          else
            echo "DEPENDENCY_GRAPH=disabled" >> $GITHUB_OUTPUT
          fi
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: ${{ steps.branch_values.outputs.DEPENDENCY_GRAPH }}
          validate-wrappers: true

      - name: Execute Gradle build
        run: ./gradlew build --no-daemon --parallel
        
      - name: Collect existing build/libs directories
        id: collect
        run: |
          paths=()
          for dir in \
            build/libs/ \
            forge/build/libs/ \
            neoforge/build/libs/ \
            fabric/build/libs/
          do
            if [ -d "$dir" ]; then
              echo "Found: $dir"
              paths+=($dir)
            fi
          done
          if [[ ${#paths[@]} -gt 0 ]]; then
            {
              echo 'paths<<EOF'
              printf '%s\n' "${dirs[@]}"
              echo 'EOF'
            } >>"$GITHUB_OUTPUT"
          fi
      - name: Upload existing JAR directories
        if: steps.collect.outputs.paths != ''
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build
          path: | 
            ${{ steps.collect.outputs.paths }}
