# This workflow publishes a Minecraft Forge project on Curseforge

name: "Publish Curseforge"

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
      curseforge-token:
        required: true
        type: string

jobs:
  publish:
    name: "Publish Curseforge"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Cache MC Assets
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publishing on Curseforge
        run: ./gradlew curseforge
        env:
          CURSEFORGE_API_KEY: ${{ inputs.curseforge-token }}
