# This workflow publishes a Minecraft Forge project on Curseforge

name: Publish Curseforge

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version that should be used to compile the code [8, 16, 17]'
        required: true
        type: number
      curseforge-id:
        description: 'The Curseforge project id'
        required: true
        type: string
      game-versions:
        description: 'A list of supported Minecraft versions'
        required: false
        default: ${undefined}
      release-type:
        description: 'The release type of the version [alpha, beta, release]'
        required: false
        type: string
        default: release
      version-prefix:
        description: 'If the versions have a prefix like "forge-", it can be added here.'
        required: false
        type: string
        default: ''
    secrets:
      curseforge-token:
        description: 'Curseforge API token'
        required: true

jobs:
  publish:
    name: Publish Curseforge
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Publishing on Curseforge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: ${{ inputs.curseforge-id }}
          curseforge-token: ${{ secrets.curseforge-token }}
          files-primary: build/libs/!(*-@(api|sources|javadoc)).jar
          files-secondary: build/libs/*-@(api|sources|javadoc).jar
          name: ${{ inputs.version-prefix }}${{ steps.get_version.outputs.result }}
          game-versions: ${{ inputs.game-versions }}
          version: ${{ inputs.version-prefix }}${{ steps.get_version.outputs.result }}
          version-type: ${{ inputs.release-type }}
          changelog-file: CHANGELOG.md
