# This workflow publishes a Minecraft Forge project on Curseforge

name: Publish Curseforge

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version that should be used to compile the code [8, 16, 17]'
        required: true
        type: number
      subproject:
        description: 'If a build is made in a subproject, this value should contain the name of that subproject'
        required: false
        type: string
        default: ''
      curseforge-id:
        description: 'The Curseforge project id'
        required: true
        type: string
      game-versions:
        description: 'A list of supported Minecraft versions'
        required: false
        type: string
        default: ${undefined}
      release-type:
        description: 'The release type of the version [alpha, beta, release]'
        required: false
        type: string
        default: release
      version-prefix:
        description: 'If the versions have a prefix like "forge-", it can be added here.'
        required: false
        type: string
        default: ''
      title-prefix:
        description: 'Adds a string to the beginning of the release title, which otherwise only contains the version.'
        required: false
        type: string
        default: ''
      loaders:
        description: 'A list of supported loaders'
        required: false
        type: string
        default: forge
      dependencies:
        description: 'A list of dependencies'
        required: false
        type: string
        default: ${undefined}
    secrets:
      github-token:
        description: 'Github token'
        required: true
      curseforge-token:
        description: 'Curseforge API token'
        required: true

jobs:
  publish:
    name: Publish Curseforge
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.github-token }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.replace('refs/tags/${{ inputs.version-prefix }}', '');

      - name: Download cached build (if any)
        id: download
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.github-token }}
          name: gradle-build
          path: .
        continue-on-error: true

      - name: Setup Java ${{ inputs.java-version }}
        if: steps.download.outcome != 'success'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        if: steps.download.outcome != 'success'
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: Execute Gradle build
        if: steps.download.outcome != 'success'
        run: ./gradlew ${{ inputs.subproject != '' && format('{0}:build', inputs.subproject) || 'build' }} --no-daemon --parallel

      - name: Publishing on Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ inputs.curseforge-id }}
          curseforge-token: ${{ secrets.curseforge-token }}
          files: |
            ${{ inputs.subproject != '' && inputs.subproject || '.' }}/build/libs/!(*-@(api|sources|javadoc)).jar
            ${{ inputs.subproject != '' && inputs.subproject || '.' }}/build/libs/*-@(api|sources|javadoc).jar
          name: ${{ inputs.title-prefix }}${{ steps.get_version.outputs.result }}
          game-versions: ${{ inputs.game-versions }}
          version: ${{ inputs.version-prefix }}${{ steps.get_version.outputs.result }}
          version-type: ${{ inputs.release-type }}
          loaders: ${{ inputs.loaders }}
          dependencies: ${{ inputs.dependencies }}
          changelog-file: CHANGELOG.md
