# This workflow triggers the build on Jitpack

name: Trigger Jitpack

on:
  workflow_call:
    inputs:
      user:
        description: 'Github username'
        required: true
        type: string
      repository:
        description: 'The name of the Github repository'
        required: true
        type: string
      tag:
        description: 'The tag, that should be built'
        required: true
        type: string

jobs:
  trigger:
    name: Trigger Jitpack
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jitpack Build
        run: |
          curl "https://jitpack.io/com/github/${{ inputs.user }}/${{ inputs.repository }}/${{ inputs.tag }}/"
