# This workflow triggers the build on Jitpack

name: Trigger Jitpack

on:
  workflow_call:

jobs:
  trigger:
    name: Trigger Jitpack
    runs-on: ubuntu-latest

    steps:
      - name: Get Version
        id: get_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.github-token }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.replace('refs/tags/', '');

      - name: Trigger Jitpack Build
        run: |
          curl "https://jitpack.io/com/github/${{ env.GITHUB_REPOSITORY }}/${{ steps.get_version.outputs.result }}/"
