# This workflow triggers the build on Jitpack

name: Trigger Jitpack

on:
  workflow_call:
    secrets:
      github-token:
        description: 'Github token'
        required: true

jobs:
  trigger:
    name: Trigger Jitpack
    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - name: Get Version
        id: get_version
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.github-token }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.replace('refs/tags/', '');

      - name: Trigger Jitpack Build
        run: |
          curl "https://jitpack.io/com/github/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/${{ steps.get_version.outputs.result }}/"
